name: Build and Deploy POC Code
on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]
jobs:
  job1:    
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Say hello to Sarvani
        run: echo "Hi Sarvani"      