name: CI

on: 
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps: 
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Say hello to Sarvani
        run: echo "Hi Sarvani"