name: Build and Deploy POC Code

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]    

jobs:
  job_setup:    
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Say hello to Sarvani
        run: echo "Hi Sarvani"      